// Livros que a Mari JÁ LEU (importados do Skoob, limpos). Semeados como lido:true.
// Formato: [titulo, autor, pais, idioma(original), ano(1ª pub|null), genero, paginas, [temas 3–5]].
// País/idioma = origem do autor/obra; ano = 1ª publicação; páginas = do print do Skoob (ou média).
export const LEITURAS_LIDOS_SEED = [
  ['A hora da estrela', 'Clarice Lispector', 'Brasil', 'Português', 1977, 'Romance', 88, ['pobreza', 'identidade', 'solidão', 'existência']],
  ['A Cantiga dos Pássaros e das Serpentes', 'Suzanne Collins', 'Estados Unidos', 'Inglês', 2020, 'Distopia / YA', 576, ['poder', 'ambição', 'sobrevivência', 'moralidade']],
  ['Travesuras de la niña mala', 'Mario Vargas Llosa', 'Peru', 'Espanhol', 2006, 'Romance', 470, ['amor obsessivo', 'desejo', 'desilusão', 'exílio']],
  ['A insustentável leveza do ser', 'Milan Kundera', 'Tchéquia', 'Tcheco', 1984, 'Romance', 312, ['amor', 'liberdade', 'política', 'sentido']],
  ['A vegetariana', 'Han Kang', 'Coreia do Sul', 'Coreano', 2007, 'Romance', 176, ['corpo', 'repressão', 'autonomia', 'loucura']],
  ['Como arruinar um casamento', 'Alison Espach', 'Estados Unidos', 'Inglês', 2024, 'Romance', 352, ['casamento', 'recomeço', 'solidão', 'humor']],
  ['Little Women', 'Louisa May Alcott', 'Estados Unidos', 'Inglês', 1868, 'Romance', 217, ['família', 'irmandade', 'amadurecimento', 'ambição feminina']],
  ['Aprender a falar com as plantas', 'Marta Orriols', 'Espanha', 'Catalão', 2018, 'Romance', 240, ['luto', 'perda', 'recomeço', 'maternidade']],
  ['Crónica de una Muerte Anunciada', 'Gabriel García Márquez', 'Colômbia', 'Espanhol', 1981, 'Romance', 144, ['honra', 'destino', 'violência', 'culpa coletiva']],
  ['O lugar', 'Annie Ernaux', 'França', 'Francês', 1983, 'Autoficção', 72, ['classe', 'pai', 'memória', 'origem']],
  ['A palavra que resta', 'Stênio Gardel', 'Brasil', 'Português', 2021, 'Romance', 152, ['amor proibido', 'analfabetismo', 'sexualidade', 'tempo']],
  ['História de quem foge e de quem fica', 'Elena Ferrante', 'Itália', 'Italiano', 2013, 'Romance', 416, ['amizade', 'classe', 'feminilidade', 'política']],
  ['História da menina perdida', 'Elena Ferrante', 'Itália', 'Italiano', 2014, 'Romance', 480, ['amizade', 'maternidade', 'perda', 'envelhecimento']],
  ['História do novo sobrenome', 'Elena Ferrante', 'Itália', 'Italiano', 2012, 'Romance', 472, ['amizade', 'casamento', 'ambição', 'Nápoles']],
  ['A anatomia de um luto', 'C. S. Lewis', 'Reino Unido', 'Inglês', 1961, 'Ensaio / Memória', 112, ['luto', 'fé', 'perda', 'Deus']],
  ['A amiga genial', 'Elena Ferrante', 'Itália', 'Italiano', 2011, 'Romance', 336, ['amizade', 'infância', 'classe', 'Nápoles']],
  ['Oração para Desaparecer', 'Socorro Acioli', 'Brasil', 'Português', 2023, 'Romance', 208, ['perda', 'fé', 'mulheres', 'sertão']],
  ['O fuzil de caça', 'Yasushi Inoue', 'Japão', 'Japonês', 1949, 'Novela', 112, ['amor proibido', 'solidão', 'culpa', 'segredo']],
  ['As intermitências da morte', 'José Saramago', 'Portugal', 'Português', 2005, 'Romance', 208, ['morte', 'mortalidade', 'amor', 'burocracia']],
  ['A morte e a morte de Quincas Berro Dágua', 'Jorge Amado', 'Brasil', 'Português', 1959, 'Novela', 120, ['morte', 'liberdade', 'boemia', 'Bahia']],
  ['O impulso', 'Ashley Audrain', 'Canadá', 'Inglês', 2021, 'Thriller psicológico', 328, ['maternidade', 'dúvida', 'trauma', 'família']],
  ['Sr. Loverman', 'Bernardine Evaristo', 'Reino Unido', 'Inglês', 2013, 'Romance', 328, ['sexualidade', 'velhice', 'casamento', 'identidade caribenha']],
  ['A cabeça do santo', 'Socorro Acioli', 'Brasil', 'Português', 2014, 'Romance', 176, ['fé', 'amor', 'sertão', 'milagre']],
  ['As brasas', 'Sándor Márai', 'Hungria', 'Húngaro', 1942, 'Romance', 176, ['amizade', 'traição', 'memória', 'honra']],
  ['A idiota', 'Elif Batuman', 'Estados Unidos', 'Inglês', 2017, 'Romance', 488, ['juventude', 'linguagem', 'amor', 'universidade']],
  ["King's Ransom", 'Ed McBain', 'Estados Unidos', 'Inglês', 1959, 'Policial', 96, ['crime', 'moralidade', 'dinheiro']],
  ['Vamos comprar um poeta', 'Afonso Cruz', 'Portugal', 'Português', 2016, 'Novela', 96, ['consumo', 'poesia', 'família', 'sociedade']],
  ['A mulher que escreveu a Bíblia', 'Moacyr Scliar', 'Brasil', 'Português', 1999, 'Romance', 168, ['fé', 'feminilidade', 'história', 'identidade']],
  ['Meu ano de descanso e relaxamento', 'Ottessa Moshfegh', 'Estados Unidos', 'Inglês', 2018, 'Romance', 240, ['alienação', 'depressão', 'consumo', 'luto']],
  ['Ouça a canção do vento / Pinball, 1973', 'Haruki Murakami', 'Japão', 'Japonês', 1979, 'Romance', 200, ['juventude', 'solidão', 'memória', 'vazio']],
  ['Pequena coreografia do adeus', 'Aline Bei', 'Brasil', 'Português', 2021, 'Romance', 288, ['luto', 'maternidade', 'tempo', 'perda']],
  ['Primeira pessoa do singular', 'Haruki Murakami', 'Japão', 'Japonês', 2020, 'Contos', 168, ['memória', 'identidade', 'música', 'surreal']],
  ['Quem vai dormir com quem?', 'Sophie Kinsella', 'Reino Unido', 'Inglês', 2018, 'Chick-lit', 320, ['amor', 'humor', 'engano']],
  ['Primatas da Park Avenue', 'Wednesday Martin', 'Estados Unidos', 'Inglês', 2015, 'Memória / Não ficção', 272, ['elite', 'maternidade', 'status', 'antropologia']],
  ['Noites Brancas', 'Fiódor Dostoiévski', 'Rússia', 'Russo', 1848, 'Novela', 93, ['solidão', 'amor', 'sonho', 'melancolia']],
  ['Beach Read', 'Emily Henry', 'Estados Unidos', 'Inglês', 2020, 'Romance', 400, ['amor', 'escrita', 'luto', 'recomeço']],
  ['Manual para Românticas Incorrigíveis', 'Gemma Townley', 'Reino Unido', 'Inglês', 2008, 'Chick-lit', 368, ['amor', 'ilusão', 'humor']],
  ['Os afetos', 'Rodrigo Hasbún', 'Bolívia', 'Espanhol', 2015, 'Romance', 128, ['família', 'revolução', 'desencontro', 'Bolívia']],
  ['A Prometida', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2021, 'YA / Romance', 344, ['amor', 'realeza', 'escolha']],
  ['A Luz que Há Entre Nós', 'Thaís Fernandez', 'Brasil', 'Português', null, 'Romance', 17, ['amor', 'distância', 'saudade']],
  ['Harry Potter e a câmara secreta', 'J.K. Rowling', 'Reino Unido', 'Inglês', 1998, 'Fantasia / YA', 252, ['amizade', 'coragem', 'preconceito', 'magia']],
  ['París puede esperar', 'Marisa Sicilia', 'Espanha', 'Espanhol', 2014, 'Romance', 47, ['amor', 'Paris', 'recomeço']],
  ['Do que eu falo quando eu falo de corrida', 'Haruki Murakami', 'Japão', 'Japonês', 2007, 'Memória / Ensaio', 152, ['corrida', 'disciplina', 'escrita', 'solidão']],
  ['O Curioso Caso de Benjamin Button', 'F. Scott Fitzgerald', 'Estados Unidos', 'Inglês', 1922, 'Conto', 56, ['tempo', 'envelhecimento', 'destino']],
  ['Me Poupe!', 'Nathalia Arcuri', 'Brasil', 'Português', 2018, 'Finanças', 176, ['dinheiro', 'educação financeira', 'consumo']],
  ['Sono', 'Haruki Murakami', 'Japão', 'Japonês', 1989, 'Conto', 116, ['insônia', 'alienação', 'rotina', 'mortalidade']],
  ['Conversas entre amigos', 'Sally Rooney', 'Irlanda', 'Inglês', 2017, 'Romance', 264, ['amor', 'amizade', 'juventude', 'classe']],
  ['A Espera', 'Lygia Fagundes Telles', 'Brasil', 'Português', 1970, 'Conto', 25, ['espera', 'memória', 'desejo']],
  ['Crepúsculo', 'Stephenie Meyer', 'Estados Unidos', 'Inglês', 2005, 'YA / Romance', 416, ['amor', 'vampiros', 'desejo', 'perigo']],
  ['O Ladrão de Raios', 'Rick Riordan', 'Estados Unidos', 'Inglês', 2005, 'Fantasia / YA', 400, ['mitologia', 'heroísmo', 'amizade', 'identidade']],
  ['O Mar de Monstros', 'Rick Riordan', 'Estados Unidos', 'Inglês', 2006, 'Fantasia / YA', 304, ['aventura', 'amizade', 'lealdade']],
  ['A Maldição do Titã', 'Rick Riordan', 'Estados Unidos', 'Inglês', 2007, 'Fantasia / YA', 336, ['sacrifício', 'profecia', 'amizade']],
  ['Querido John', 'Nicholas Sparks', 'Estados Unidos', 'Inglês', 2006, 'Romance', 384, ['amor', 'guerra', 'distância', 'sacrifício']],
  ['Anna e o Beijo Francês', 'Stephanie Perkins', 'Estados Unidos', 'Inglês', 2010, 'YA / Romance', 432, ['amor', 'juventude', 'Paris']],
  ['Comédias para se ler na escola', 'Luis Fernando Verissimo', 'Brasil', 'Português', 2001, 'Crônica / Humor', 145, ['humor', 'cotidiano', 'crônica']],
  ['Eleanor & Park', 'Rainbow Rowell', 'Estados Unidos', 'Inglês', 2013, 'YA / Romance', 328, ['primeiro amor', 'abuso', 'marginalização']],
  ['Auto da Barca do Inferno / Farsa de Inês Pereira', 'Gil Vicente', 'Portugal', 'Português', 1517, 'Teatro', 96, ['moralidade', 'sátira', 'religião']],
  ['Assim é a Vida, Charlie Brown!', 'Charles M. Schulz', 'Estados Unidos', 'Inglês', null, 'Quadrinhos', 136, ['amizade', 'infância', 'humor']],
  ['O Gato Preto', 'Edgar Allan Poe', 'Estados Unidos', 'Inglês', 1843, 'Conto', 40, ['culpa', 'loucura', 'crime']],
  ['Farsa de Inês Pereira', 'Gil Vicente', 'Portugal', 'Português', 1523, 'Teatro', 64, ['sátira', 'casamento', 'moralidade']],
  ['Mais comédias para se ler na escola', 'Luis Fernando Verissimo', 'Brasil', 'Português', 2002, 'Crônica / Humor', 144, ['humor', 'cotidiano', 'crônica']],
  ['Auto da Barca do Inferno', 'Gil Vicente', 'Portugal', 'Português', 1517, 'Teatro', 97, ['moralidade', 'religião', 'sátira']],
  ['Amor e Cuba Libre', 'Álvaro Cardoso Gomes', 'Brasil', 'Português', null, 'Romance juvenil', 100, ['amor', 'juventude']],
  ['Morta de Medo', 'Norah McClintock', 'Canadá', 'Inglês', null, 'YA / Suspense', 270, ['medo', 'mistério', 'adolescência']],
  ['Cuidado: Garoto Apaixonado', 'Toni Brandão', 'Brasil', 'Português', null, 'Infantojuvenil', 79, ['amor', 'adolescência']],
  ['Só Chateando (Irada!)', 'Andy Griffiths', 'Austrália', 'Inglês', 2002, 'Infantojuvenil / Humor', 138, ['humor', 'infância']],
  ['Só Loucura! (Irada!)', 'Andy Griffiths', 'Austrália', 'Inglês', 2002, 'Infantojuvenil / Humor', 203, ['humor', 'infância']],
  ['Um presente para minha filha', 'Lidia María Riba', 'Argentina', 'Espanhol', null, 'Não ficção', 43, ['maternidade', 'amor', 'conselhos']],
  ['Os criminosos vieram para o chá', 'Stella Carr', 'Brasil', 'Português', null, 'Infantojuvenil / Mistério', 120, ['mistério', 'aventura', 'humor']],
  ['Acredite se Quiser!', 'Laé de Souza', 'Brasil', 'Português', null, 'Crônica', 127, ['cotidiano', 'humor']],
  ['10 anos com Mafalda', 'Quino', 'Argentina', 'Espanhol', 1973, 'Quadrinhos', 190, ['política', 'infância', 'sátira']],
  ['Espectro azul', 'Ana Carolina Aires', 'Brasil', 'Português', null, 'Romance', 112, ['amor', 'mistério']],
  ['Ideias para adiar o fim do mundo', 'Ailton Krenak', 'Brasil', 'Português', 2019, 'Ensaio', 104, ['natureza', 'indígena', 'capitalismo', 'futuro']],
  ['Mulheres', 'Carol Rossetti', 'Brasil', 'Português', 2015, 'Ilustração / Feminismo', 160, ['feminismo', 'identidade', 'corpo', 'liberdade']],
  ['Sonetos de Camões', 'Luís de Camões', 'Portugal', 'Português', 1595, 'Poesia', 224, ['amor', 'saudade', 'tempo']],
  ['O Hipster', 'J. A. Hazeley e J. P. Morris', 'Reino Unido', 'Inglês', 2016, 'Humor', 52, ['humor', 'sátira']],
  ['Os encontros', 'J. A. Hazeley e J. P. Morris', 'Reino Unido', 'Inglês', 2016, 'Humor', 52, ['humor', 'relacionamentos']],
  ['Por Que os Edifícios Ficam de Pé', 'Mario Salvadori', 'Estados Unidos', 'Inglês', 1980, 'Não ficção', 384, ['arquitetura', 'engenharia', 'ciência']],
  ['Três Peças', 'Paloma Vidal', 'Brasil', 'Português', 2017, 'Teatro', 104, ['memória', 'exílio', 'identidade']],
  ['Chiclete: O Incrível Garoto que Encolhe', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 120, ['infância', 'humor', 'aventura']],
  ['Judy Moody - a Garota Detetive', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 205, ['infância', 'amizade', 'mistério']],
  ['Judy Moody Quer A Fama!', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 156, ['infância', 'humor', 'escola']],
  ['Judy Moody Salva o Mundo', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 176, ['infância', 'meio ambiente', 'humor']],
  ['Judy Moody - Adivinha o Futuro', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 171, ['infância', 'humor', 'imaginação']],
  ['Judy Moody - Doutora', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 182, ['infância', 'humor', 'escola']],
  ['Judy Moody Declares Independence!', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 160, ['infância', 'autonomia', 'humor']],
  ['Judy Moody - A Volta ao Mundo Em 8 1/2 Dias', 'Megan McDonald', 'Estados Unidos', 'Inglês', null, 'Infantil', 173, ['infância', 'aventura', 'humor']],
  ['Tú también naciste desnudito', 'Álvaro de Laiglesia', 'Espanha', 'Espanhol', null, 'Humor', 270, ['humor', 'sátira', 'sociedade']],
  ['Nunca juntos mas ao mesmo tempo', 'Wagner Schwartz', 'Brasil', 'Português', null, 'Romance', 176, ['corpo', 'arte', 'identidade']],
  ['A Caderneta Vermelha', 'Antoine Laurain', 'França', 'Francês', 2014, 'Romance', 192, ['amor', 'acaso', 'Paris', 'mistério']],
  ['Pluft, o fantasminha', 'Maria Clara Machado', 'Brasil', 'Português', 1955, 'Teatro infantil', 46, ['medo', 'amizade', 'infância']],
  ['Sonho de uma noite de verão', 'William Shakespeare', 'Inglaterra', 'Inglês', 1600, 'Teatro', 128, ['amor', 'magia', 'sonho', 'confusão']],
  ['O burguês fidalgo', 'Molière', 'França', 'Francês', 1670, 'Teatro', 96, ['vaidade', 'classe', 'sátira']],
  ['O Despertar da Primavera', 'Frank Wedekind', 'Alemanha', 'Alemão', 1891, 'Teatro', 178, ['adolescência', 'sexualidade', 'repressão']],
  ['Amanhã você vai entender', 'Rebecca Stead', 'Estados Unidos', 'Inglês', 2009, 'Infantojuvenil', 224, ['amizade', 'tempo', 'mistério']],
  ['Édipo Rei', 'Sófocles', 'Grécia', 'Grego', -429, 'Tragédia', 112, ['destino', 'verdade', 'culpa']],
  ['Amigos Para a Vida', 'Andrew Norriss', 'Reino Unido', 'Inglês', 2015, 'Infantojuvenil', 208, ['amizade', 'luto', 'saúde mental']],
  ['Cidade dos Ossos', 'Cassandra Clare', 'Estados Unidos', 'Inglês', 2007, 'Fantasia / YA', 476, ['magia', 'identidade', 'amor', 'segredos']],
  ['Alice no País das Maravilhas', 'Lewis Carroll', 'Reino Unido', 'Inglês', 1865, 'Fantasia', 224, ['imaginação', 'infância', 'absurdo']],
  ['Mau Começo', 'Lemony Snicket', 'Estados Unidos', 'Inglês', 1999, 'Infantojuvenil', 152, ['orfandade', 'adversidade', 'humor sombrio']],
  ['Impecáveis', 'Sara Shepard', 'Estados Unidos', 'Inglês', 2007, 'YA / Mistério', 336, ['segredos', 'amizade', 'mentira']],
  ['Maldosas', 'Sara Shepard', 'Estados Unidos', 'Inglês', 2006, 'YA / Mistério', 296, ['segredos', 'amizade', 'mentira']],
  ['Poderosa 2', 'Sérgio Klein', 'Brasil', 'Português', null, 'YA', 148, ['adolescência', 'amor']],
  ['Poderosa', 'Sérgio Klein', 'Brasil', 'Português', null, 'YA', 185, ['adolescência', 'amor']],
  ['Mary Ventura e o nono reino', 'Sylvia Plath', 'Estados Unidos', 'Inglês', 2019, 'Conto', 48, ['alienação', 'controle', 'despertar']],
  ['Melhores poemas de Paulo Leminski', 'Paulo Leminski', 'Brasil', 'Português', 1996, 'Poesia', 224, ['amor', 'cotidiano', 'concisão']],
  ['Noite na Taverna', 'Álvares de Azevedo', 'Brasil', 'Português', 1855, 'Contos', 139, ['morte', 'amor', 'ultrarromantismo']],
  ['As Vantagens de Ser Invisível', 'Stephen Chbosky', 'Estados Unidos', 'Inglês', 1999, 'YA', 224, ['adolescência', 'trauma', 'amizade', 'pertencimento']],
  ['Vida de Droga', 'Walcyr Carrasco', 'Brasil', 'Português', null, 'Infantojuvenil', 176, ['drogas', 'adolescência', 'escolhas']],
  ['E Agora Mãe?', 'Isabel Vieira', 'Brasil', 'Português', null, 'Infantojuvenil', 93, ['família', 'adolescência']],
  ['O Primeiro Amor de Laurinha', 'Pedro Bandeira', 'Brasil', 'Português', null, 'Infantojuvenil', 108, ['primeiro amor', 'infância']],
  ['Minha Primeira Paixão', 'Pedro Bandeira', 'Brasil', 'Português', null, 'Infantojuvenil', 88, ['amor', 'juventude']],
  ['Ou Isto ou Aquilo', 'Cecília Meireles', 'Brasil', 'Português', 1964, 'Poesia infantil', 96, ['infância', 'escolha', 'brincadeira']],
  ['O Fantástico Mistério de Feiurinha', 'Pedro Bandeira', 'Brasil', 'Português', 1986, 'Infantojuvenil', 80, ['contos de fada', 'mistério', 'humor']],
  ['Diálogos impossíveis', 'Luis Fernando Verissimo', 'Brasil', 'Português', 2012, 'Crônica / Humor', 176, ['humor', 'cotidiano']],
  ['O Sofá Estampado', 'Lygia Bojunga', 'Brasil', 'Português', 1980, 'Infantojuvenil', 107, ['imaginação', 'família', 'liberdade']],
  ['A Bolsa Amarela', 'Lygia Bojunga', 'Brasil', 'Português', 1976, 'Infantojuvenil', 115, ['infância', 'desejos', 'liberdade']],
  ['Pollyanna', 'Eleanor H. Porter', 'Estados Unidos', 'Inglês', 1913, 'Infantojuvenil', 181, ['otimismo', 'gratidão', 'adversidade']],
  ['Lola e o Garoto da Casa ao Lado', 'Stephanie Perkins', 'Estados Unidos', 'Inglês', 2011, 'YA / Romance', 288, ['amor', 'identidade', 'juventude']],
  ['Os Delírios de Consumo de Becky Bloom', 'Sophie Kinsella', 'Reino Unido', 'Inglês', 2000, 'Chick-lit', 432, ['consumo', 'dívida', 'humor']],
  ['Olhai os lírios do campo', 'Erico Verissimo', 'Brasil', 'Português', 1938, 'Romance', 288, ['amor', 'classe', 'ambição', 'culpa']],
  ['Pygmalion', 'Bernard Shaw', 'Irlanda', 'Inglês', 1913, 'Teatro', 176, ['classe', 'linguagem', 'transformação']],
  ['A Cidade e as Serras', 'Eça de Queiroz', 'Portugal', 'Português', 1901, 'Romance', 191, ['civilização', 'natureza', 'modernidade']],
  ['Antígona', 'Sófocles', 'Grécia', 'Grego', -441, 'Tragédia', 110, ['lei', 'consciência', 'família', 'poder']],
  ['Til', 'José de Alencar', 'Brasil', 'Português', 1872, 'Romance', 320, ['amor', 'sertão', 'destino']],
  ['O Cortiço', 'Aluísio Azevedo', 'Brasil', 'Português', 1890, 'Romance / Naturalismo', 256, ['pobreza', 'ambição', 'coletividade']],
  ['As Regras do Amor', 'Pamela Wells', 'Estados Unidos', 'Inglês', 2006, 'YA / Romance', 336, ['amor', 'amizade', 'regras']],
  ['Diário de um Banana', 'Jeff Kinney', 'Estados Unidos', 'Inglês', 2007, 'Infantojuvenil / Humor', 217, ['escola', 'amizade', 'humor']],
  ['A Probabilidade Estatística do Amor à Primeira Vista', 'Jennifer E. Smith', 'Estados Unidos', 'Inglês', 2012, 'YA / Romance', 224, ['acaso', 'amor', 'destino']],
  ['Divergente', 'Veronica Roth', 'Estados Unidos', 'Inglês', 2011, 'Distopia / YA', 504, ['identidade', 'coragem', 'sociedade', 'escolha']],
  ['Memórias póstumas de Brás Cubas', 'Machado de Assis', 'Brasil', 'Português', 1881, 'Romance', 236, ['morte', 'ironia', 'sociedade', 'vaidade']],
  ['Extraordinário', 'R. J. Palacio', 'Estados Unidos', 'Inglês', 2012, 'Infantojuvenil', 320, ['diferença', 'bondade', 'empatia', 'bullying']],
  ['Insurgente', 'Veronica Roth', 'Estados Unidos', 'Inglês', 2012, 'Distopia / YA', 512, ['guerra', 'identidade', 'lealdade']],
  ['Capitães da Areia', 'Jorge Amado', 'Brasil', 'Português', 1937, 'Romance', 296, ['infância', 'pobreza', 'marginalização', 'Bahia']],
  ['Garotas da Rua Beacon Vol. 3', 'Annie Bryant', 'Estados Unidos', 'Inglês', null, 'YA', 267, ['amizade', 'adolescência']],
  ['Garotas da Rua Beacon Vol. 2', 'Annie Bryant', 'Estados Unidos', 'Inglês', null, 'YA', 280, ['amizade', 'adolescência']],
  ['Piores Inimigas / Melhores Amigas', 'Annie Bryant', 'Estados Unidos', 'Inglês', null, 'YA', 254, ['amizade', 'adolescência']],
  ['Ela Disse, Ele Disse', 'Thalita Rebouças', 'Brasil', 'Português', null, 'YA / Humor', 192, ['amor', 'adolescência', 'humor']],
  ['Fala Sério, Mãe!', 'Thalita Rebouças', 'Brasil', 'Português', 2006, 'YA / Humor', 172, ['família', 'adolescência', 'humor']],
  ['Apaixonada por Palavras', 'Paula Pimenta', 'Brasil', 'Português', null, 'YA', 160, ['amor', 'escrita']],
  ['Fani em Busca do Final Feliz', 'Paula Pimenta', 'Brasil', 'Português', null, 'YA', 608, ['amor', 'juventude', 'sonhos']],
  ['Minha Vida Fora de Série #2', 'Paula Pimenta', 'Brasil', 'Português', null, 'YA', 424, ['amor', 'amadurecimento', 'juventude']],
  ['Fani Na Terra Da Rainha', 'Paula Pimenta', 'Brasil', 'Português', null, 'YA', 328, ['amor', 'juventude', 'sonhos']],
  ['O Roteiro Inesperado De Fani', 'Paula Pimenta', 'Brasil', 'Português', null, 'YA', 424, ['amor', 'juventude', 'sonhos']],
  ['Minha Vida Fora de Série #1', 'Paula Pimenta', 'Brasil', 'Português', null, 'YA', 408, ['amor', 'amadurecimento', 'juventude']],
  ['A Estreia de Fani', 'Paula Pimenta', 'Brasil', 'Português', null, 'YA', 336, ['amor', 'juventude', 'sonhos']],
  ['A Rainha', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2014, 'YA / Romance', 87, ['amor', 'realeza']],
  ['A Sereia', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2016, 'YA', 328, ['amor', 'sacrifício', 'mar']],
  ['Contos da Seleção: O Príncipe & O Guarda', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2013, 'YA', 257, ['amor', 'realeza']],
  ['A Herdeira', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2015, 'YA / Romance', 416, ['amor', 'realeza', 'escolha']],
  ['A Coroa', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2016, 'YA / Romance', 312, ['amor', 'realeza', 'escolha']],
  ['A Escolha', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2014, 'YA / Romance', 352, ['amor', 'realeza', 'escolha']],
  ['A Elite', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2013, 'YA / Romance', 360, ['amor', 'realeza', 'competição']],
  ['A Seleção', 'Kiera Cass', 'Estados Unidos', 'Inglês', 2012, 'YA / Distopia', 363, ['amor', 'classe', 'competição']],
  ['Os 12 Signos de Valentina', 'Ray Tavares', 'Brasil', 'Português', null, 'YA', 392, ['astrologia', 'amor', 'adolescência']],
  ['A Garota Americana', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2002, 'YA', 352, ['amor', 'política', 'adolescência']],
  ['Tamanho 42 Não é Gorda', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2005, 'Chick-lit / Mistério', 416, ['corpo', 'mistério', 'humor']],
  ['Cabeça de Vento', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2004, 'YA', 320, ['amor', 'adolescência']],
  ['A Rainha da Fofoca', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2006, 'Chick-lit', 432, ['amor', 'humor', 'trabalho']],
  ['Quase Pronta', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2003, 'YA', 288, ['amor', 'fama', 'adolescência']],
  ['Pegando Fogo!', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2009, 'Chick-lit / Sobrenatural', 304, ['amor', 'poderes', 'humor']],
  ['Pântano de Sangue', 'Pedro Bandeira', 'Brasil', 'Português', null, 'Infantojuvenil / Mistério', 192, ['aventura', 'mistério', 'ecologia']],
  ['Pessoas normais', 'Sally Rooney', 'Irlanda', 'Inglês', 2018, 'Romance', 264, ['amor', 'classe', 'juventude', 'saúde mental']],
  ['A droga da obediência', 'Pedro Bandeira', 'Brasil', 'Português', 1984, 'Infantojuvenil / Aventura', 194, ['amizade', 'coragem', 'aventura']],
  ['Quem É Você, Alasca?', 'John Green', 'Estados Unidos', 'Inglês', 2005, 'YA', 240, ['luto', 'juventude', 'busca', 'culpa']],
  ['Cidades de Papel', 'John Green', 'Estados Unidos', 'Inglês', 2008, 'YA', 368, ['identidade', 'idealização', 'aventura']],
  ['O Teorema Katherine', 'John Green', 'Estados Unidos', 'Inglês', 2006, 'YA', 304, ['amor', 'identidade', 'fracasso', 'humor']],
  ['A culpa é das estrelas', 'John Green', 'Estados Unidos', 'Inglês', 2012, 'YA', 224, ['amor', 'doença', 'morte', 'sentido']],
  ['A Droga do Amor', 'Pedro Bandeira', 'Brasil', 'Português', 1994, 'Infantojuvenil', 128, ['amor', 'juventude', 'aventura']],
  ['O menino do pijama listrado', 'John Boyne', 'Irlanda', 'Inglês', 2006, 'Romance histórico', 190, ['guerra', 'inocência', 'amizade', 'Holocausto']],
  ['A Esperança', 'Suzanne Collins', 'Estados Unidos', 'Inglês', 2010, 'Distopia / YA', 424, ['guerra', 'revolução', 'trauma']],
  ['A Terra das Sombras', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2000, 'YA / Sobrenatural', 288, ['fantasmas', 'amor', 'poderes']],
  ['Iracema', 'José de Alencar', 'Brasil', 'Português', 1865, 'Romance indianista', 82, ['amor', 'colonização', 'mito', 'perda']],
  ['Memórias de um Sargento de Milícias', 'Manuel Antônio de Almeida', 'Brasil', 'Português', 1854, 'Romance', 168, ['malandragem', 'sociedade', 'humor']],
  ['Em Chamas', 'Suzanne Collins', 'Estados Unidos', 'Inglês', 2009, 'Distopia / YA', 416, ['revolução', 'sobrevivência', 'resistência']],
  ['Melancia', 'Marian Keyes', 'Irlanda', 'Inglês', 1995, 'Chick-lit', 490, ['maternidade', 'abandono', 'recomeço', 'humor']],
  ['Vidas secas', 'Graciliano Ramos', 'Brasil', 'Português', 1938, 'Romance', 174, ['seca', 'pobreza', 'sertão', 'dignidade']],
  ['O Diário da Princesa', 'Meg Cabot', 'Estados Unidos', 'Inglês', 2000, 'YA', 284, ['identidade', 'realeza', 'adolescência']],
  ['Jogos Vorazes', 'Suzanne Collins', 'Estados Unidos', 'Inglês', 2008, 'Distopia / YA', 400, ['sobrevivência', 'opressão', 'sacrifício']],
  ['O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'França', 'Francês', 1943, 'Fábula', 96, ['infância', 'amizade', 'sentido', 'solidão']],
  ['Harry Potter e a pedra filosofal', 'J.K. Rowling', 'Reino Unido', 'Inglês', 1997, 'Fantasia / YA', 264, ['magia', 'amizade', 'coragem', 'pertencimento']],
];
