// BILHETE DE USO ÚNICO (set/2026) — as matérias da piauí, edições 218 a 229,
// da planilha que a Mari mandou em 10/set. Gerado por script a partir do Excel;
// não editar à mão. Sai do código junto com `ensurePiauiSet26` assim que estiver
// gravado no documento dela.
//
// tipo: 'reportagem' | 'esquina' | 'outro' (outro = ficção, poesia, cartuns,
// quadrinhos, portfólio, cartas, diário do geraldo, piauí herald, capa).
export const PIAUI_EDICOES_SET26 = [{"n": 229, "mes": "outubro de 2025"}, {"n": 228, "mes": "setembro de 2025"}, {"n": 225, "mes": "junho de 2025"}, {"n": 224, "mes": "maio de 2025"}, {"n": 223, "mes": "abril de 2025"}, {"n": 222, "mes": "março de 2025"}, {"n": 221, "mes": "fevereiro de 2025"}, {"n": 220, "mes": "janeiro de 2025"}, {"n": 219, "mes": "dezembro de 2024"}, {"n": 218, "mes": "novembro de 2024"}];

export const PIAUI_MATERIAS_SET26 = [
  {"id": "pz218-01", "ed": 218, "tipo": "reportagem", "titulo": "Seca literária", "linha": "O fim da Xingu, única livraria num raio de mil quilômetros na Amazônia"},
  {"id": "pz218-02", "ed": 218, "tipo": "outro", "titulo": "As falésias", "linha": "Nada exceto o aborrecimento une nossa família"},
  {"id": "pz218-03", "ed": 218, "tipo": "outro", "titulo": "Lesmas que rompem em brasas e desafiam os dedos a cutucá-las"},
  {"id": "pz218-04", "ed": 218, "tipo": "reportagem", "titulo": "A longa arte de Antonio Carlos Jobim", "linha": "A riqueza e a originalidade de seu Cancioneiro ainda estão por ser reconhecidas"},
  {"id": "pz218-05", "ed": 218, "tipo": "reportagem", "titulo": "Dentes postiços", "linha": "Oswald de Andrade, da grande guerra ao amor maior"},
  {"id": "pz218-06", "ed": 218, "tipo": "reportagem", "titulo": "Riso sem meio-termo", "linha": "Ricardo Araújo Pereira e sua defesa do humor incondicional – com uma ajudinha de Machado de Assis"},
  {"id": "pz218-07", "ed": 218, "tipo": "reportagem", "chapeu": "grandes figuras do mundo animal", "titulo": "Em memória de um gato", "linha": "Aderbal e nossos dezoito anos", "autor": "Roberto Kaz"},
  {"id": "pz218-08", "ed": 218, "tipo": "outro", "chapeu": "portfólio", "titulo": "A ver navios", "linha": "Um ferro-velho de cargueiros em Bangladesh", "autor": "Christian Cravo"},
  {"id": "pz218-09", "ed": 218, "tipo": "reportagem", "chapeu": "dossiê piauí_umane", "titulo": "O complexo: parte II — o dinheiro, sempre", "linha": "A segunda reportagem da série aborda as agruras, os rigores e as ganâncias para bancar o maior sistema de saúde do mundo", "autor": "Fabiane Leite"},
  {"id": "pz218-10", "ed": 218, "tipo": "reportagem", "chapeu": "flagrantes do congresso", "titulo": "O sequestrador", "linha": "Uma história exemplar mostra como Lira capturou o orçamento secreto em seu favor", "autor": "Breno Pires"},
  {"id": "pz218-11", "ed": 218, "tipo": "outro", "chapeu": "cartas", "titulo": "O deleite de um texto longo e emocionante de um autor conciso"},
  {"id": "pz218-12", "ed": 218, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Adão Iturrusgarai", "autor": "Adão Iturrusgarai"},
  {"id": "pz218-13", "ed": 218, "tipo": "esquina", "chapeu": "esquina", "titulo": "Amor no coletivo", "linha": "A Ruivinha do Rodilândia recebe uma proposta romântica", "autor": "Sandro Aurélio Jr."},
  {"id": "pz218-14", "ed": 218, "tipo": "esquina", "chapeu": "esquina", "titulo": "Axé no Olimpo", "linha": "A primeira trans no topo da indústria da moda", "autor": "João Batista Jr."},
  {"id": "pz218-15", "ed": 218, "tipo": "esquina", "chapeu": "esquina", "titulo": "A morte é uma festa", "linha": "A cidade paraense que celebra Finados com música e bebida", "autor": "Leandra Souza"},
  {"id": "pz218-16", "ed": 218, "tipo": "esquina", "chapeu": "esquina", "titulo": "Cidade de comer", "linha": "A plataforma que mapeia árvores frutíferas mundo afora", "autor": "Bernardo Esteves"},
  {"id": "pz218-17", "ed": 218, "tipo": "esquina", "chapeu": "esquina", "titulo": "Baile dos excelentíssimos", "linha": "Banda de juízes agita festas da magistratura paulista", "autor": "Guilherme Henrique"},
  {"id": "pz218-18", "ed": 218, "tipo": "esquina", "chapeu": "esquina", "titulo": "A mão e a máquina", "linha": "As mudanças tecnológicas na taquigrafia do Congresso", "autor": "Pedro Tavares"},
  {"id": "pz218-19", "ed": 218, "tipo": "esquina", "chapeu": "esquina", "titulo": "Meia-noite em Paraty", "linha": "Dois prodígios literários da França se conhecem na Flip", "autor": "Ana Clara Costa"},
  {"id": "pz218-20", "ed": 218, "tipo": "reportagem", "chapeu": "questões eleitorais", "titulo": "Bolsonarismo Shrek", "linha": "Como as urnas afetaram as coalizões que devem se enfrentar em 2026", "autor": "André Singer"},
  {"id": "pz218-21", "ed": 218, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Que Chou do Chuchu é esse?", "linha": "Amarrei o que resta das minhas madeixas em chuquinhas coloridas"},
  {"id": "pz218-22", "ed": 218, "tipo": "reportagem", "chapeu": "vultos da república", "titulo": "O homem da planilha", "linha": "Gilberto Kassab prepara o PSD para os próximos trezentos anos", "autor": "Luigi Mazza"},
  {"id": "pz218-23", "ed": 218, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "A ameaça autoritária, ainda", "linha": "Eis aí o recado das urnas nas eleições municipais", "autor": "Fernando de Barros e Silva"},
  {"id": "pz219-01", "ed": 219, "tipo": "outro", "titulo": "Golpearam a capa"},
  {"id": "pz219-02", "ed": 219, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Arnaldo Branco"},
  {"id": "pz219-03", "ed": 219, "tipo": "outro", "titulo": "Perfis perturbadores & capitanias hereditárias"},
  {"id": "pz219-04", "ed": 219, "tipo": "esquina", "chapeu": "esquina", "titulo": "Coisas da vida", "linha": "Uma escritora enfrenta as dores fantasmas e as reais"},
  {"id": "pz219-05", "ed": 219, "tipo": "esquina", "chapeu": "esquina", "titulo": "Território acadêmico", "linha": "Uma indígena entre o doutorado e o Congresso"},
  {"id": "pz219-06", "ed": 219, "tipo": "esquina", "chapeu": "esquina", "titulo": "Isso se come", "linha": "A invenção do acrônimo que redimiu as plantas marginais"},
  {"id": "pz219-07", "ed": 219, "tipo": "esquina", "chapeu": "esquina", "titulo": "Lugar de fala", "linha": "A ONG que ajuda pessoas com gagueira a se aceitarem", "autor": "Pedro Tavares"},
  {"id": "pz219-08", "ed": 219, "tipo": "esquina", "chapeu": "esquina", "titulo": "Nação em escombros", "linha": "USP inaugura um centro de estudos sobre a Palestina", "autor": "Carlos Adriano"},
  {"id": "pz219-09", "ed": 219, "tipo": "esquina", "chapeu": "esquina", "titulo": "A turma do caranguejo", "linha": "Tardes e noites no Satyricon, onde se farta a elite carioca", "autor": "Ana Clara Costa"},
  {"id": "pz219-10", "ed": 219, "tipo": "esquina", "chapeu": "esquina", "titulo": "As colmeias de terra", "linha": "A arqueologia ajuda povos da floresta a proteger a Amazônia", "autor": "Bernardo Esteves"},
  {"id": "pz219-11", "ed": 219, "tipo": "reportagem", "chapeu": "despedida", "titulo": "Libélulas subversivas", "linha": "A intuição do fotógrafo Evandro Teixeira e o instante decisivo", "autor": "Flavio Pinheiro"},
  {"id": "pz219-12", "ed": 219, "tipo": "outro", "chapeu": "poesia", "titulo": "Seis poemas em prosa", "linha": "Coleciono árvores num canto da memória", "autor": "Fernando Paixão"},
  {"id": "pz219-13", "ed": 219, "tipo": "outro", "chapeu": "ficção", "titulo": "Riso imotivado", "linha": "Tanta tristeza naquela vida, e tanta alegria na outra", "autor": "Marilene Felinto"},
  {"id": "pz219-14", "ed": 219, "tipo": "reportagem", "chapeu": "ensaio", "titulo": "O mundo bloqueado", "linha": "A façanha artística de Beckett – e sua decifração por Adorno", "autor": "Roberto Schwarz"},
  {"id": "pz219-15", "ed": 219, "tipo": "reportagem", "chapeu": "questões de cinema e de dor II", "titulo": "Toda ficção é memória", "linha": "Relatos da criação de Malu, um filme que, sem pretender, realizou um processo de cura", "autor": "Pedro Freire"},
  {"id": "pz219-16", "ed": 219, "tipo": "reportagem", "chapeu": "questões de cinema e de dor I", "titulo": "Relato de uma certa tragédia", "linha": "Um filme reflete sobre a situação dos libaneses, dos indígenas e dos desterrados de todo o mundo", "autor": "Consuelo Dieguez"},
  {"id": "pz219-17", "ed": 219, "tipo": "outro", "chapeu": "portfólio", "titulo": "Corona news", "linha": "A pandemia segundo jornais verdadeiros e imaginários", "autor": "Eloar Guazzelli Filho"},
  {"id": "pz219-18", "ed": 219, "tipo": "reportagem", "chapeu": "diário de nova york", "titulo": "Não sei se me viram, mas eu os vi", "linha": "Entre a poesia e a política durante as eleições americanas", "autor": "Ricardo Aleixo"},
  {"id": "pz219-19", "ed": 219, "tipo": "reportagem", "chapeu": "dossiê piauí_umane", "titulo": "O complexo: parte III — o SUS bate à porta", "linha": "Na terceira reportagem da série, as histórias de três famílias que dependem do sistema público de saúde", "autor": "Tiago Coelho"},
  {"id": "pz219-20", "ed": 219, "tipo": "reportagem", "chapeu": "almanaque do lobby II", "titulo": "De salgadinhos e refrigerantes", "linha": "Como a indústria tem atuado na reforma tributária para baratear os produtos ultraprocessados", "autor": "Marcello Fragano Baird"},
  {"id": "pz219-21", "ed": 219, "tipo": "reportagem", "chapeu": "almanaque do lobby I", "titulo": "De fumaças e vapores", "linha": "Como a indústria trabalha para confundir a plateia e legalizar o cigarro eletrônico", "autor": "Camille Lichotti"},
  {"id": "pz219-22", "ed": 219, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Ninguém segura o Joca", "linha": "Obrigado, terroristas, vocês sabem que eu tenho valor!"},
  {"id": "pz219-23", "ed": 219, "tipo": "reportagem", "chapeu": "anais da rataria", "titulo": "O golpista", "linha": "As 533 digitais de Bolsonaro na articulação para “virar a mesa”", "autor": "Breno Pires"},
  {"id": "pz219-24", "ed": 219, "tipo": "reportagem", "chapeu": "questões vultosas II", "titulo": "Trump e o fascismo", "linha": "O que esperar?", "autor": "Timothy Snyder"},
  {"id": "pz219-25", "ed": 219, "tipo": "reportagem", "chapeu": "questões vultosas I", "titulo": "Os imperdoáveis", "linha": "São eles. Serão eles?", "autor": "Fernando de Barros e Silva"},
  {"id": "pz220-01", "ed": 220, "tipo": "reportagem", "titulo": "A farra das apostas", "linha": "Os influenciadores e as bets", "autor": "João Batista Jr. e Alessandra Medina"},
  {"id": "pz220-02", "ed": 220, "tipo": "reportagem", "titulo": "O voto e seu enigma", "linha": "É hora de pensar a democracia além da urna", "autor": "Miguel Lago"},
  {"id": "pz220-03", "ed": 220, "tipo": "reportagem", "titulo": "Tudo pelo Botafogo", "linha": "Sandro Aurélio Jr. conta sua saga para ver o campeão da América"},
  {"id": "pz220-04", "ed": 220, "tipo": "reportagem", "titulo": "Cartazes da gentileza", "linha": "Oito imagens da arte nos trens do Japão", "autor": "Armando Antenore"},
  {"id": "pz220-05", "ed": 220, "tipo": "reportagem", "titulo": "A tropa da saúde", "linha": "Se fosse uma empresa privada, o SUS seria o maior empregador do mundo", "autor": "Mônica Manir"},
  {"id": "pz220-06", "ed": 220, "tipo": "reportagem", "chapeu": "questões latino-americanas", "titulo": "A virada", "linha": "Como o governo Lula mudou de rota na sua relação com Nicolás Maduro", "autor": "Consuelo Dieguez"},
  {"id": "pz220-07", "ed": 220, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "Os incendiários", "linha": "O jogo entre a Faria Lima e o governo", "autor": "Ana Clara Costa"},
  {"id": "pz220-08", "ed": 220, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Eu sou o chester da política brasileira", "linha": "Não tenho a exuberância de um pavão, mas sirvo bem para servir sempre"},
  {"id": "pz220-09", "ed": 220, "tipo": "reportagem", "chapeu": "anais da pauleira", "titulo": "“É muito legal quando você morre”", "linha": "A última turnê do Sepultura, a mais celebrada banda brasileira de heavy metal", "autor": "Gilberto Porcidonio"},
  {"id": "pz220-10", "ed": 220, "tipo": "reportagem", "chapeu": "questões literárias", "titulo": "“Sou um problema, não um homem”", "linha": "Os acertos e desacertos de J. D. Salinger", "autor": "Jorio Dauster"},
  {"id": "pz220-11", "ed": 220, "tipo": "reportagem", "chapeu": "anais da história", "titulo": "O lado B do Barão", "linha": "A marginália do Barão do Rio Branco, o chanceler que ajudou a definir as fronteiras do Brasil", "autor": "Cristiane Costa e Luís Cláudio Villafañe G. Santos"},
  {"id": "pz220-12", "ed": 220, "tipo": "outro", "chapeu": "ficção", "titulo": "A barata, Macabéa e Lisette", "linha": "Três contos claricianos", "autor": "Evando Nascimento"},
  {"id": "pz220-13", "ed": 220, "tipo": "outro", "chapeu": "poesia", "titulo": "Crocodilos", "linha": "Onde as feras verde-musgo convivem sem jaulas", "autor": "Natasha Belfort Palmeira"},
  {"id": "pz220-14", "ed": 220, "tipo": "outro", "chapeu": "piauí herald", "titulo": "The Bolsozapp Herald", "linha": "Em edição extra por motivo de força maior, a trama golpista nos subterrâneos da rataria", "autor": "Olegário Ribamar"},
  {"id": "pz220-15", "ed": 220, "tipo": "reportagem", "chapeu": "despedida", "titulo": "“Me confesso cansado e burro”", "linha": "Uma carta inédita de Dalton Trevisan para o escritor Otto Lara Resende"},
  {"id": "pz220-16", "ed": 220, "tipo": "esquina", "chapeu": "esquina", "titulo": "Cuidando dos mortos", "linha": "Um médico patologista enfrenta o preconceito contra a dissecção de cadáveres", "autor": "Artur Maciel Rodrigues"},
  {"id": "pz220-17", "ed": 220, "tipo": "esquina", "chapeu": "esquina", "titulo": "Jogos de poder na Gávea", "linha": "A disputa por uma quadra de tênis na Zona Sul do Rio", "autor": "Carolina Bottino"},
  {"id": "pz220-18", "ed": 220, "tipo": "esquina", "chapeu": "esquina", "titulo": "Construtor de imagens", "linha": "Em Santos, a arte proletária de um pedreiro fotógrafo", "autor": "Lara Musa"},
  {"id": "pz220-19", "ed": 220, "tipo": "esquina", "chapeu": "esquina", "titulo": "Sede de justiça", "linha": "A pajé cearense que lutou por água para sua aldeia", "autor": "Gabriela Lopes"},
  {"id": "pz220-20", "ed": 220, "tipo": "esquina", "chapeu": "esquina", "titulo": "Mãe, o que é isso?", "linha": "As estudantes gaúchas que combatem a pobreza menstrual", "autor": "Érica Wallauer Alves"},
  {"id": "pz220-21", "ed": 220, "tipo": "esquina", "chapeu": "esquina", "titulo": "Graça alcançada", "linha": "Em meio à depressão, o restauro de bonecas", "autor": "Pedro Novaes"},
  {"id": "pz220-22", "ed": 220, "tipo": "esquina", "chapeu": "esquina", "titulo": "Maria das ninfas", "linha": "Uma bela da tarde na noite agitada do Recife", "autor": "Felipe Fernandes"},
  {"id": "pz220-23", "ed": 220, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Reinaldo Figueiredo", "autor": "Reinaldo Figueiredo"},
  {"id": "pz220-24", "ed": 220, "tipo": "outro", "chapeu": "cartas", "titulo": "Depois de um tempo pegando maresia, a piauí perde a aspereza do papel"},
  {"id": "pz221-01", "ed": 221, "tipo": "reportagem", "titulo": "Imagens proibidas", "linha": "Um grande filme é interditado", "autor": "Bernardo Esteves"},
  {"id": "pz221-02", "ed": 221, "tipo": "reportagem", "titulo": "As coisas podem dar certo", "linha": "João Moreira Salles faz a crônica de um ano glorioso"},
  {"id": "pz221-03", "ed": 221, "tipo": "reportagem", "titulo": "“É a canalha no poder”", "linha": "Eduardo Escorel reúne as cartas de um ano fatídico"},
  {"id": "pz221-04", "ed": 221, "tipo": "reportagem", "titulo": "Chave mágica nas favelas", "linha": "As invasões de casa pela PM", "autor": "Armando Antenore"},
  {"id": "pz221-05", "ed": 221, "tipo": "reportagem", "titulo": "Pressão judicial", "linha": "A enxurrada de processos contra o SUS", "autor": "Allan de Abreu"},
  {"id": "pz221-06", "ed": 221, "tipo": "reportagem", "chapeu": "questões iluministas", "titulo": "O novo obscurantismo", "linha": "O misticismo anticientífico atingiu os mais altos escalões da política americana e agora impulsiona as autocracias mundo afora", "autor": "Anne Applebaum"},
  {"id": "pz221-07", "ed": 221, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "Yes, nós temos banana", "linha": "O remake de Vale tudo e a nova ordem global", "autor": "Fernando de Barros e Silva"},
  {"id": "pz221-08", "ed": 221, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "O primeiro ano do resto de nossas vidas", "linha": "Desde que President’Lula assumiu, o povo pode comer brioche nas padarias artesanais"},
  {"id": "pz221-09", "ed": 221, "tipo": "reportagem", "chapeu": "questões culturais", "titulo": "Assistindo ao luxo", "linha": "Retratos ficcionais da alta elite se tornaram uma obsessão. São sátiras ou homenagens?", "autor": "Alejandro Chacoff"},
  {"id": "pz221-10", "ed": 221, "tipo": "outro", "chapeu": "ficção", "titulo": "O que você faria?", "linha": "Os viúvos te ofenderão, os órfãos trarão sentimentos confusos", "autor": "Evandro Cruz Silva"},
  {"id": "pz221-11", "ed": 221, "tipo": "outro", "chapeu": "questionário", "titulo": "Responda, se for capaz", "linha": "As perguntas incômodas do escritor Max Frisch"},
  {"id": "pz221-12", "ed": 221, "tipo": "outro", "chapeu": "poesia", "titulo": "Ilusões de nuvens", "linha": "Uma plantação de algodão imensa com ninfas néfeles", "autor": "Felipe Franco Munhoz"},
  {"id": "pz221-13", "ed": 221, "tipo": "reportagem", "chapeu": "despedida", "titulo": "O antípoda de Trump", "linha": "Jimmy Carter deixou como legado a defesa da paz, dos direitos humanos e do meio ambiente", "autor": "Consuelo Dieguez"},
  {"id": "pz221-14", "ed": 221, "tipo": "esquina", "chapeu": "esquina", "titulo": "Os rios invisíveis", "linha": "Placas de rua lembram cursos d’água soterrados na capital mineira", "autor": "Karla Monteiro"},
  {"id": "pz221-15", "ed": 221, "tipo": "esquina", "chapeu": "esquina", "titulo": "O amigo do velho", "linha": "O homem que pautou a vida por Luiz Carlos Prestes", "autor": "Felippe Aníbal"},
  {"id": "pz221-16", "ed": 221, "tipo": "esquina", "chapeu": "esquina", "titulo": "Futebol nômade", "linha": "A interminável peregrinação de um time do Rio de Janeiro", "autor": "João Felipe Carvalho"},
  {"id": "pz221-17", "ed": 221, "tipo": "esquina", "chapeu": "esquina", "titulo": "Os livros do messias", "linha": "Um sebo paulistano segue em frente depois da morte do fundador", "autor": "Guilherme Henrique"},
  {"id": "pz221-18", "ed": 221, "tipo": "esquina", "chapeu": "esquina", "titulo": "Maratona da morte", "linha": "Um atleta coleciona medalhas e velórios", "autor": "Adriano Alves"},
  {"id": "pz221-19", "ed": 221, "tipo": "esquina", "chapeu": "esquina", "titulo": "Segredos da fé", "linha": "O artista católico que decora lojas maçônicas", "autor": "Tatiane de Assis"},
  {"id": "pz221-20", "ed": 221, "tipo": "esquina", "chapeu": "esquina", "titulo": "O sol em Kafka", "linha": "Uma sueca busca luz entre as sombras do escritor", "autor": "Duanne Ribeiro"},
  {"id": "pz221-21", "ed": 221, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Allan Sieber", "autor": "Allan Sieber"},
  {"id": "pz221-22", "ed": 221, "tipo": "outro", "chapeu": "cartas", "titulo": "Uma ode e uma vaia aos diários"},
  {"id": "pz222-01", "ed": 222, "tipo": "reportagem", "titulo": "Anatomia de um escândalo sexual", "linha": "Ana Clara Costa reconstitui a queda do ministro Silvio Almeida"},
  {"id": "pz222-02", "ed": 222, "tipo": "reportagem", "titulo": "A tropa da desinformação", "linha": "Como milicianos russos operam na África", "autor": "Morgane Le Cam"},
  {"id": "pz222-03", "ed": 222, "tipo": "reportagem", "titulo": "O império da branquitude", "linha": "Um artigo inédito de Abdias Nascimento sobre o racismo nacional"},
  {"id": "pz222-04", "ed": 222, "tipo": "reportagem", "titulo": "A longa coreografia", "linha": "O grupo Corpo completa 50 anos", "autor": "Karla Monteiro"},
  {"id": "pz222-05", "ed": 222, "tipo": "outro", "chapeu": "portfólio", "titulo": "Naquele tempo", "linha": "Cenas de um mundo que ainda cabia em folhas de jornal", "autor": "Eddy Posthuma de Boer (1931-2021)"},
  {"id": "pz222-06", "ed": 222, "tipo": "reportagem", "chapeu": "anais da antropologia", "titulo": "O reencontro", "linha": "Noventa anos depois, indígenas do povo Boe veem pela primeira vez, em Paris, os objetos coletados em seu território pelo casal Lévi-Strauss", "autor": "João Kelmer e Maria Luísa Lucas"},
  {"id": "pz222-07", "ed": 222, "tipo": "reportagem", "chapeu": "dossiê piauí_umane", "titulo": "O complexo: parte final — A tecnologia e o dilema", "linha": "O SUS já se provou capaz de oferecer terapias de alta complexidade, mas enfrenta o desafio: como universalizar esses procedimentos?", "autor": "Bernardo Esteves"},
  {"id": "pz222-08", "ed": 222, "tipo": "reportagem", "chapeu": "questões de pilhagem", "titulo": "Os escândalos do museu", "linha": "O Museu Britânico enfrenta acusações de roubar o patrimônio cultural de outros países – enquanto lida com um rombo material dentro de casa", "autor": "Rebecca Mead"},
  {"id": "pz222-09", "ed": 222, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "A motosserra e o jabuti", "linha": "Duas personagens, duas peças de propaganda – e um momento revelador", "autor": "Fernando de Barros e Silva"},
  {"id": "pz222-10", "ed": 222, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Trump vai taxar o chuchu", "linha": "Sou mesmo um fio desencapado"},
  {"id": "pz222-11", "ed": 222, "tipo": "outro", "chapeu": "quadrinhos", "titulo": "Nunca mais!… E mais… E mais… E mais…", "linha": "Pelo poder dos quadrinhos, dois cartunistas se desenham na Faixa de Gaza", "autor": "Art Spiegelman e Joe Sacco"},
  {"id": "pz222-12", "ed": 222, "tipo": "reportagem", "chapeu": "questões literárias", "titulo": "Por que não escrevo", "linha": "Às vezes, quando nem presto atenção, eu vivo", "autor": "Débora Vázquez"},
  {"id": "pz222-13", "ed": 222, "tipo": "outro", "chapeu": "poesia", "titulo": "Forragem/Forage", "linha": "... mas na vida, quando os sonhos de uma criança se incendeiam?", "autor": "Arthur Sze"},
  {"id": "pz222-14", "ed": 222, "tipo": "reportagem", "chapeu": "despedida", "titulo": "Roliúde", "linha": "Os bastidores de Bye bye Brasil, o filme mais importante de Cacá Diegues", "autor": "Lauro Escorel"},
  {"id": "pz222-15", "ed": 222, "tipo": "esquina", "chapeu": "esquina", "titulo": "Gênero literário", "linha": "Clubes de leitura se dedicam apenas às escritoras mulheres", "autor": "Karine Dalla Valle"},
  {"id": "pz222-16", "ed": 222, "tipo": "esquina", "chapeu": "esquina", "titulo": "Amuleto às avessas", "linha": "Uma cadelinha festeira e a má fase do Fluminense", "autor": "Armando Antenore"},
  {"id": "pz222-17", "ed": 222, "tipo": "esquina", "chapeu": "esquina", "titulo": "Trama ancestral", "linha": "Artista argentina ganha o mundo com a tecelagem", "autor": "Tatiane de Assis"},
  {"id": "pz222-18", "ed": 222, "tipo": "esquina", "chapeu": "esquina", "titulo": "Pelo telefone", "linha": "Uma atriz baiana e seu Teatro de Ouvido", "autor": "Samil Chalupe"},
  {"id": "pz222-19", "ed": 222, "tipo": "esquina", "chapeu": "esquina", "titulo": "O app dourado", "linha": "O compositor carioca que votou no Oscar", "autor": "João Batista Jr."},
  {"id": "pz222-20", "ed": 222, "tipo": "esquina", "chapeu": "esquina", "titulo": "Vitória nas quadras", "linha": "Uma jovem brasileira brilha no tênis de cadeira de rodas", "autor": "Felipe Fernandes"},
  {"id": "pz222-21", "ed": 222, "tipo": "esquina", "chapeu": "esquina", "titulo": "Esperando Davi", "linha": "Seis horas de teatro do absurdo na eleição do presidente do Senado", "autor": "Camille Lichotti"},
  {"id": "pz222-22", "ed": 222, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Caco Galhardo e Renato Terra", "autor": "Caco Galhardo e Renato Terra"},
  {"id": "pz222-23", "ed": 222, "tipo": "outro", "chapeu": "cartas", "titulo": "Nossas regras de semântica e sintaxe para textos sobre o Botafogo"},
  {"id": "pz223-01", "ed": 223, "tipo": "reportagem", "titulo": "O alvo é você", "linha": "Breno Pires e o vale-tudo das operadoras de plano de saúde"},
  {"id": "pz223-02", "ed": 223, "tipo": "reportagem", "titulo": "Os desmandos da CBF", "linha": "Allan de Abreu e a tumultuada gestão de Ednaldo Rodrigues"},
  {"id": "pz223-03", "ed": 223, "tipo": "reportagem", "titulo": "21 dias de trauma", "linha": "Angélica Santa Cruz e a internação compulsória de uma escritora"},
  {"id": "pz223-04", "ed": 223, "tipo": "reportagem", "titulo": "\"Cheguei do nada\"", "linha": "Pedro Tavares e a ascensão de Rick Azevedo, o vereador contra a escala 6x1"},
  {"id": "pz223-05", "ed": 223, "tipo": "reportagem", "chapeu": "investigações culturais", "titulo": "A desconhecida", "linha": "A busca pela identidade de uma mulher em uma foto histórica e o mergulho no mundo das artes plásticas de Nova York", "autor": "Simone Duarte"},
  {"id": "pz223-06", "ed": 223, "tipo": "outro", "chapeu": "portfólio", "titulo": "Arco-íris amazônico", "linha": "Um passeio pelas cores e luzes do Pará", "autor": "Luiz Braga"},
  {"id": "pz223-07", "ed": 223, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "O verniz do vale-tudo", "linha": "Pazuello, a imprensa e a democracia", "autor": "Fernando de Barros e Silva"},
  {"id": "pz223-08", "ed": 223, "tipo": "reportagem", "chapeu": "memórias editoriais", "titulo": "As duas faces de um amigo", "linha": "Paulo Francis, o afetuoso e o cruel", "autor": "Luiz Schwarcz"},
  {"id": "pz223-09", "ed": 223, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Geraldo é tech. Geraldo é pop. Geraldo é tudo.", "linha": "Tô manjando tudo dessa juventude contemporânea"},
  {"id": "pz223-10", "ed": 223, "tipo": "reportagem", "chapeu": "peripécias vernáculas", "titulo": "Um dicionário heterodoxo", "linha": "Jantar é a janta dos herdeiros, e kombucha, um refrigerante de vinagre", "autor": "Eduardo Bento"},
  {"id": "pz223-11", "ed": 223, "tipo": "reportagem", "chapeu": "despedida", "titulo": "Réquiem para um chichá", "linha": "A queda de uma árvore secular no Largo do Arouche, em São Paulo", "autor": "Mônica Manir"},
  {"id": "pz223-12", "ed": 223, "tipo": "outro", "chapeu": "poesia", "titulo": "Oito poetas da África", "linha": "Uma usina criativa que segue a todo vapor", "autor": "Salgado Maranhão"},
  {"id": "pz223-13", "ed": 223, "tipo": "outro", "chapeu": "ficção", "titulo": "O monge, o licuri e o Makotinho de Iansã", "linha": "Haviam me avisado da similaridade entre terreiros de candomblé e templos japoneses", "autor": "Cidinha da Silva"},
  {"id": "pz223-14", "ed": 223, "tipo": "esquina", "chapeu": "esquina", "titulo": "Maricá, c’est moi", "linha": "O carnaval político de Washington Quaquá", "autor": "Camille Lichotti"},
  {"id": "pz223-15", "ed": 223, "tipo": "esquina", "chapeu": "esquina", "titulo": "O detetive altruísta", "linha": "Um sertanejo à procura de pessoas desaparecidas", "autor": "Armando Antenore"},
  {"id": "pz223-16", "ed": 223, "tipo": "esquina", "chapeu": "esquina", "titulo": "FL, de Faria Limer", "linha": "A alfaiataria que borda as iniciais da elite econômica", "autor": "João Batista Jr."},
  {"id": "pz223-17", "ed": 223, "tipo": "esquina", "chapeu": "esquina", "titulo": "Carpetes da República", "linha": "O funcionário que renovou o visual do Senado", "autor": "Pedro Tavares"},
  {"id": "pz223-18", "ed": 223, "tipo": "esquina", "chapeu": "esquina", "titulo": "Templo da confusão", "linha": "Os enroscos em torno de um prédio da maçonaria carioca", "autor": "Danilo Marques"},
  {"id": "pz223-19", "ed": 223, "tipo": "esquina", "chapeu": "esquina", "titulo": "Musa dos pescados", "linha": "A jovem que conquistou as redes sociais empunhando um facão", "autor": "Leandra Souza"},
  {"id": "pz223-20", "ed": 223, "tipo": "esquina", "chapeu": "esquina", "titulo": "O guardião da tela", "linha": "O funcionário mais antigo do cinema mais antigo do Recife", "autor": "Felipe Fernandes"},
  {"id": "pz223-21", "ed": 223, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Galvão Bertazzi", "autor": "Galvão Bertazzi"},
  {"id": "pz223-22", "ed": 223, "tipo": "outro", "chapeu": "cartas", "titulo": "Notas mandinguentas, higiênicas e um novo leitor a bordo"},
  {"id": "pz224-01", "ed": 224, "tipo": "reportagem", "titulo": "Operação resgate", "linha": "Os bastidores da tentativa de salvamento do Banco Master", "autor": "Consuelo Dieguez"},
  {"id": "pz224-02", "ed": 224, "tipo": "reportagem", "titulo": "As peripécias do rei Allard XIV", "linha": "Quem é o francês que se tornou um dínamo imobiliário de São Paulo", "autor": "João Batista Jr."},
  {"id": "pz224-03", "ed": 224, "tipo": "reportagem", "titulo": "“Não posso me queixar”", "linha": "A vida extraordinária de Flora Purim", "autor": "Ana Clara Costa"},
  {"id": "pz224-04", "ed": 224, "tipo": "reportagem", "titulo": "Revisitando os gigantes", "linha": "O estudo que pode mudar a história dos grandes mamíferos da América do Sul", "autor": "Bernardo Esteves"},
  {"id": "pz224-05", "ed": 224, "tipo": "reportagem", "chapeu": "dossiê piauí", "titulo": "Geração democracia: parte I — A promessa e o corre", "linha": "Numa sociedade apaixonada pela desigualdade, uma empreendedora luta contra a quase pobreza", "autor": "José Henrique Bortoluci"},
  {"id": "pz224-06", "ed": 224, "tipo": "outro", "chapeu": "portfólio", "titulo": "Ainda submersos", "linha": "Um ano depois da pior catástrofe ambiental da história gaúcha", "autor": "Gideon Mendel"},
  {"id": "pz224-07", "ed": 224, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "A esquerda acossada", "linha": "Entre um Congresso hostil, um mercado raivoso e um mundo em desordem", "autor": "Fernando de Barros e Silva"},
  {"id": "pz224-08", "ed": 224, "tipo": "reportagem", "chapeu": "questões educacionais", "titulo": "A escola integral", "linha": "Há quarenta anos, era inaugurado no Rio de Janeiro o primeiro Ciep", "autor": "Alexandre Benoit"},
  {"id": "pz224-09", "ed": 224, "tipo": "reportagem", "chapeu": "vultos da literatura", "titulo": "A festa tardia", "linha": "Sigrid Nunez e seus celebrados romances sobre o luto", "autor": "Alejandro Chacoff, de Nova York"},
  {"id": "pz224-10", "ed": 224, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Popcorn, ice-cream and chuchu", "linha": "Minha influência no governo é acachapante"},
  {"id": "pz224-11", "ed": 224, "tipo": "reportagem", "chapeu": "questões culturais", "titulo": "Visões da diversidade", "linha": "A expansão simultânea da fotografia e da etnografia pelo planeta", "autor": "Paulo Antonio Paranaguá"},
  {"id": "pz224-12", "ed": 224, "tipo": "outro", "chapeu": "ficção", "titulo": "Um animal fabuloso", "linha": "Entre as recordações da Argentina, procuro um lugar onde haja um cavalo que se possa abraçar", "autor": "Samanta Schweblin"},
  {"id": "pz224-13", "ed": 224, "tipo": "reportagem", "chapeu": "despedida", "titulo": "Adeus à arte", "linha": "Os brasileiros não estão preparados para o gesto poético de Memphis Depay", "autor": "Gregorio Duvivier"},
  {"id": "pz224-14", "ed": 224, "tipo": "esquina", "chapeu": "esquina", "titulo": "A corda e a caçamba", "linha": "Dois procuradores contra um aparato de esquecimento", "autor": "Angélica Santa Cruz"},
  {"id": "pz224-15", "ed": 224, "tipo": "esquina", "chapeu": "esquina", "titulo": "Breque geral", "linha": "Um mineiro à frente da greve dos entregadores de aplicativos", "autor": "Danilo Marques"},
  {"id": "pz224-16", "ed": 224, "tipo": "esquina", "chapeu": "esquina", "titulo": "A memória dos jardins", "linha": "Um aprendiz de Burle Marx e o legado do paisagista", "autor": "Amanda Gorziza"},
  {"id": "pz224-17", "ed": 224, "tipo": "esquina", "chapeu": "esquina", "titulo": "Vinde a mim os bichinhos", "linha": "Animais de estimação animam uma missa na Espanha", "autor": "Mateus Campos, de Sevilha"},
  {"id": "pz224-18", "ed": 224, "tipo": "esquina", "chapeu": "esquina", "titulo": "Letras fluviais", "linha": "A arte dos pintores de barcos da Amazônia", "autor": "Leandra Souza"},
  {"id": "pz224-19", "ed": 224, "tipo": "esquina", "chapeu": "esquina", "titulo": "Flor desabrocha", "linha": "O primeiro álbum da neta de Gilberto Gil", "autor": "Tiago Coelho"},
  {"id": "pz224-20", "ed": 224, "tipo": "esquina", "chapeu": "esquina", "titulo": "A difícil transparência", "linha": "Na República Tcheca, um brasileiro descobre a arte em vidro", "autor": "Gabriel Ferreira Morais, de Slunečná"},
  {"id": "pz224-21", "ed": 224, "tipo": "outro", "chapeu": "poesia", "titulo": "Os princípios por cumprir", "autor": "André Capilé"},
  {"id": "pz224-22", "ed": 224, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Alberto Benett", "autor": "Alberto Benett"},
  {"id": "pz224-23", "ed": 224, "tipo": "outro", "chapeu": "capa", "titulo": "Carnaval das criaturas, de Vito Quintans", "linha": "A identificação de cada um dos 31 vilões na capa desta edição"},
  {"id": "pz224-24", "ed": 224, "tipo": "outro", "chapeu": "cartas", "titulo": "Bola quadrada, foto redonda"},
  {"id": "pz225-01", "ed": 225, "tipo": "reportagem", "titulo": "A pilhagem do INSS", "linha": "Breno Pires e a origem do esquema que tirou bilhões dos aposentados"},
  {"id": "pz225-02", "ed": 225, "tipo": "reportagem", "titulo": "A vida ao Sul de Trump", "linha": "Marcos Nobre e o lugar do Brasil na nova ordem geopolítica"},
  {"id": "pz225-03", "ed": 225, "tipo": "reportagem", "titulo": "“Perdi o controle”", "linha": "João Batista Jr. e a derrocada de George Santos, o deputado brasileiro nos Estados Unidos"},
  {"id": "pz225-04", "ed": 225, "tipo": "reportagem", "titulo": "Ouro em alto-mar", "linha": "Allan de Abreu e as artimanhas criminais de um austríaco no Brasil"},
  {"id": "pz225-05", "ed": 225, "tipo": "reportagem", "chapeu": "labirintos do brasil", "titulo": "O burocrata", "linha": "Camille Lichotti narra como um funcionário público e seus colegas desvendaram (quase) todos os segredos do Orçamento da União", "autor": "Camille Lichotti"},
  {"id": "pz225-06", "ed": 225, "tipo": "reportagem", "chapeu": "questões médicas", "titulo": "Miliamperes no cérebro", "linha": "Avanços tecnológicos abrem nova era nas cirurgias psiquiátricas", "autor": "Fernando Tadeu Moraes"},
  {"id": "pz225-07", "ed": 225, "tipo": "reportagem", "chapeu": "despedida", "titulo": "O sorriso da raposa", "linha": "Jacob Palis, o homem que ajudou a erguer a matemática brasileira", "autor": "Fernando Tadeu Moraes"},
  {"id": "pz225-08", "ed": 225, "tipo": "outro", "chapeu": "portfólio", "titulo": "Tião voador", "linha": "O encontro do fotógrafo com o drone ao retratar o Instituto Terra, em Minas Gerais", "autor": "Sebastião Salgado (1944-2025)"},
  {"id": "pz225-09", "ed": 225, "tipo": "reportagem", "chapeu": "dossiê piauí", "titulo": "Geração Democracia: parte II — A luta e o impasse", "linha": "A democracia que temos e a democracia por vir", "autor": "José Henrique Bortoluci"},
  {"id": "pz225-10", "ed": 225, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "O mar virou sertão", "linha": "A armadilha do agro e o paradoxo do governo", "autor": "Fernando de Barros e Silva"},
  {"id": "pz225-11", "ed": 225, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Nasce a esquerda reborn", "linha": "... e ninguém vai nos segurar"},
  {"id": "pz225-12", "ed": 225, "tipo": "reportagem", "chapeu": "anais do luto", "titulo": "Pepe & Manuela"},
  {"id": "pz225-13", "ed": 225, "tipo": "esquina", "chapeu": "esquina", "titulo": "Os economistas franciscanos", "linha": "O movimento católico que defende uma economia capaz de gerar não só riqueza, mas também alegria – para todos", "autor": "Danilo Marques"},
  {"id": "pz225-14", "ed": 225, "tipo": "esquina", "chapeu": "esquina", "titulo": "A cegonha não pousa aqui", "linha": "A cidade onde a maternidade fechou há quinze anos", "autor": "Leandro Aguiar"},
  {"id": "pz225-15", "ed": 225, "tipo": "esquina", "chapeu": "esquina", "titulo": "Tremor e destemor", "linha": "O poeta Francisco Alvim faz rara participação em festival", "autor": "Francesca Angiolillo"},
  {"id": "pz225-16", "ed": 225, "tipo": "esquina", "chapeu": "esquina", "titulo": "Arrastão da saudade", "linha": "Uma professora supera o luto na festa do Pavulagem", "autor": "Leandra Souza"},
  {"id": "pz225-17", "ed": 225, "tipo": "esquina", "chapeu": "esquina", "titulo": "Gabriel e as abençoadas", "linha": "As lições de um dedetizador a uma cliente apavorada", "autor": "Consuelo Dieguez"},
  {"id": "pz225-18", "ed": 225, "tipo": "esquina", "chapeu": "esquina", "titulo": "Frutos sonoros", "linha": "A arte de converter cabaças em música", "autor": "Felipe Fernandes"},
  {"id": "pz225-19", "ed": 225, "tipo": "esquina", "chapeu": "esquina", "titulo": "A língua do contra", "linha": "O dialeto criado no Rio para driblar a repressão", "autor": "Maria Júlia Vieira"},
  {"id": "pz225-20", "ed": 225, "tipo": "outro", "chapeu": "cartas", "titulo": "Saiba tudo sobre Dirceu, o missivista contumaz"},
  {"id": "pz225-21", "ed": 225, "tipo": "outro", "chapeu": "poesia", "titulo": "Você acredita em Damasco à primeira vista?", "autor": "Ghayath Almadhoun"},
  {"id": "pz225-22", "ed": 225, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Reinaldo Figueiredo", "autor": "Reinaldo Figueiredo"},
  {"id": "pz228-01", "ed": 228, "tipo": "reportagem", "titulo": "A armação estrangeira", "linha": "Como Eduardo Bolsonaro tramou contra o Brasil", "autor": "João Batista Jr."},
  {"id": "pz228-02", "ed": 228, "tipo": "reportagem", "titulo": "O criptoboy", "linha": "O jovem que lavou bilhões do crime com moeda virtual", "autor": "Allan de Abreu"},
  {"id": "pz228-03", "ed": 228, "tipo": "reportagem", "titulo": "Segurança em tempo real", "linha": "A tecnologia contra o feminicídio no Distrito Federal", "autor": "Consuelo Dieguez"},
  {"id": "pz228-04", "ed": 228, "tipo": "reportagem", "titulo": "Cansando de ser sexy", "linha": "A trajetória turbulenta de Luísa Matsushita", "autor": "Danilo Marques"},
  {"id": "pz228-05", "ed": 228, "tipo": "reportagem", "titulo": "A morte de um obituário", "linha": "Um erro e uma mudança radical nos céus", "autor": "João Moreira Salles"},
  {"id": "pz228-06", "ed": 228, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "Os “normais” e sua hora", "linha": "E uma pitada de desfaçatez de classe", "autor": "Fernando de Barros e Silva"},
  {"id": "pz228-07", "ed": 228, "tipo": "reportagem", "chapeu": "questões venenosas", "titulo": "Sociedade para a morte", "linha": "Como uma mineradora, o STF e o governador Ronaldo Caiado se movem para adiar o fechamento de uma mina que mata", "autor": "Solano Nascimento"},
  {"id": "pz228-08", "ed": 228, "tipo": "reportagem", "chapeu": "dossiê piauí", "titulo": "Geração democracia: parte V — O cuidado e a desolação", "linha": "Uma sociedade deve ser avaliada pela forma como cuida dos mais frágeis", "autor": "José Henrique Bortoluci"},
  {"id": "pz228-09", "ed": 228, "tipo": "reportagem", "chapeu": "questões transumanas", "titulo": "Somos todos Ítaca", "linha": "Um ensaio sobre a obsolescência", "autor": "Olavo Amaral"},
  {"id": "pz228-10", "ed": 228, "tipo": "outro", "chapeu": "quadrinhos", "titulo": "Free William", "linha": "Salvem os pinguins!", "autor": "Allan Sieber e Eduardo Souza Lima"},
  {"id": "pz228-11", "ed": 228, "tipo": "reportagem", "chapeu": "crônica geopolítica", "titulo": "A variedade vertiginosa da China", "linha": "Diferenças geográficas e culturais ganham escala dramática no país continental", "autor": "Tash Aw"},
  {"id": "pz228-12", "ed": 228, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Nem maçã ou morango. É hora do chuchu do amor", "linha": "Libelu anda assustada com meu desassombro"},
  {"id": "pz228-13", "ed": 228, "tipo": "outro", "chapeu": "ficção", "titulo": "Em primeira pessoa", "linha": "Olhei para as fotos por mais um tempo, tentando memorizar os rostos desses irmãos que eu só conhecia de passagem", "autor": "Bruna Dantas Lobato"},
  {"id": "pz228-14", "ed": 228, "tipo": "reportagem", "chapeu": "despedida", "titulo": "Reizinho desse chão", "linha": "A trajetória de Arlindo Cruz reverenciada num samba do Império Serrano", "autor": "Leonardo Lichote"},
  {"id": "pz228-15", "ed": 228, "tipo": "esquina", "chapeu": "esquina", "titulo": "A outra da outra", "linha": "Homônima de stylist de Preta Gil é esmigalhada na internet", "autor": "Angélica Santa Cruz"},
  {"id": "pz228-16", "ed": 228, "tipo": "esquina", "chapeu": "esquina", "titulo": "Verdes anos", "linha": "A segunda COP de uma menina paraibana", "autor": "Pedro Tavares"},
  {"id": "pz228-17", "ed": 228, "tipo": "esquina", "chapeu": "esquina", "titulo": "O conselheiro e a mata", "linha": "Um clã político em choque com as leis ambientais", "autor": "Allan de Abreu"},
  {"id": "pz228-18", "ed": 228, "tipo": "esquina", "chapeu": "esquina", "titulo": "Fungos turísticos", "linha": "O caminho dos cogumelos na serra fluminense", "autor": "Amanda Gorziza"},
  {"id": "pz228-19", "ed": 228, "tipo": "esquina", "chapeu": "esquina", "titulo": "Quilombo sobrenatural", "linha": "O realismo fantástico de um filme feito em Goiás", "autor": "Tiago Coelho"},
  {"id": "pz228-20", "ed": 228, "tipo": "esquina", "chapeu": "esquina", "titulo": "O lixo e a palafita", "linha": "A degradação turística das ilhas de Belém", "autor": "Leandra Souza"},
  {"id": "pz228-21", "ed": 228, "tipo": "esquina", "chapeu": "esquina", "titulo": "Cubo branco, arte negra", "linha": "Uma galeria de artistas periféricos na Zona Sul do Rio", "autor": "Tatiane de Assis"},
  {"id": "pz228-22", "ed": 228, "tipo": "outro", "chapeu": "cartuns", "titulo": "Cartuns de Tracey K. Berglund", "autor": "Tracey K. Berglund"},
  {"id": "pz228-23", "ed": 228, "tipo": "outro", "chapeu": "cartas", "titulo": "O leitor e todas as notícias que cabem ser impressas"},
  {"id": "pz229-01", "ed": 229, "tipo": "reportagem", "titulo": "O golpe no Supremo...", "linha": "Camille Lichotti relata um julgamento inédito na história do Brasil"},
  {"id": "pz229-02", "ed": 229, "tipo": "reportagem", "titulo": "...e no Congresso", "linha": "Ana Clara Costa conta os bastidores da articulação para anistiar Bolsonaro"},
  {"id": "pz229-03", "ed": 229, "tipo": "reportagem", "titulo": "Hackeando a democracia", "linha": "Leonardo Martins Barbosa escreve sobre o partido digital bolsonarista"},
  {"id": "pz229-04", "ed": 229, "tipo": "reportagem", "titulo": "O dilema da BR-319", "linha": "Bernardo Esteves percorreu a estrada amazônica para contar o que se perde e o que se ganha com o seu asfaltamento"},
  {"id": "pz229-05", "ed": 229, "tipo": "reportagem", "chapeu": "questões vultosas", "titulo": "A pátria em disputa", "linha": "Projeto autoritário sofre revés, mas segue vivo", "autor": "Fernando de Barros e Silva"},
  {"id": "pz229-06", "ed": 229, "tipo": "reportagem", "chapeu": "dossiê democracia", "titulo": "Geração democracia: parte VI — a aula e o truque", "linha": "Sonhos, pesadelos e disputas em torno da educação no Brasil", "autor": "José Henrique Bortoluci"},
  {"id": "pz229-07", "ed": 229, "tipo": "reportagem", "chapeu": "questões educacionais", "titulo": "Universidade à venda", "linha": "Como Romeu Zema quer se livrar de um complexo universitário que atende 22 mil alunos", "autor": "Leandro Aguiar"},
  {"id": "pz229-08", "ed": 229, "tipo": "outro", "chapeu": "portfólio", "titulo": "De volta à terra", "linha": "Um artista em diálogo com as próprias origens", "autor": "Antonio Obá e Tatiane de Assis"},
  {"id": "pz229-09", "ed": 229, "tipo": "reportagem", "chapeu": "questões morais", "titulo": "O dilema", "linha": "Como manter a decência vivendo em uma sociedade indecente", "autor": "Ian Buruma"},
  {"id": "pz229-10", "ed": 229, "tipo": "reportagem", "chapeu": "questões judaicas", "titulo": "Armadilhas do novo antissemitismo", "linha": "A extrema direita adota os judeus como vítimas da esquerda, enquanto a própria comunidade judaica transforma em algozes os seus membros progressistas", "autor": "Michel Gherman"},
  {"id": "pz229-11", "ed": 229, "tipo": "reportagem", "chapeu": "questões brasileiríssimas", "titulo": "Uma mulher", "linha": "A vida de Mirtes de Souza, antes e depois da morte do seu filho de 5 anos", "autor": "Thallys Braga"},
  {"id": "pz229-12", "ed": 229, "tipo": "reportagem", "chapeu": "questões familiares", "titulo": "Pai e filho", "linha": "A história de Augusto e Milton Nascimento – que recebeu o diagnóstico de demência", "autor": "João Batista Jr."},
  {"id": "pz229-13", "ed": 229, "tipo": "reportagem", "chapeu": "questões invertebradas", "titulo": "Homenagem de uma aracnofóbica", "linha": "Canibais, venenosas, traiçoeiras. Podemos aprender a amar as aranhas?", "autor": "Kathryn Schulz"},
  {"id": "pz229-14", "ed": 229, "tipo": "reportagem", "chapeu": "cantoras do brasil", "titulo": "A protagonista", "linha": "As glórias e angústias de Liniker", "autor": "Thallys Braga"},
  {"id": "pz229-15", "ed": 229, "tipo": "outro", "chapeu": "diário do geraldo", "titulo": "Socorro! Anistiaram Aécio Neves!", "linha": "É a reviravolta dos que não foram!"},
  {"id": "pz229-16", "ed": 229, "tipo": "reportagem", "chapeu": "micromemórias", "titulo": "O mal das oficinas literárias", "linha": "Não concebo a escrita como uma atividade ilustre, mas furtiva", "autor": "Fabio Morábito"},
  {"id": "pz229-17", "ed": 229, "tipo": "outro", "chapeu": "piauí herald", "titulo": "Papelaria caserna", "linha": "Os melhores cadernos pro seu golpe de Estado", "autor": "Olegário Ribamar"},
  {"id": "pz229-18", "ed": 229, "tipo": "outro", "chapeu": "ficção", "titulo": "Amor de várzea", "linha": "Tu foi feito pra correr, então corre, porra!", "autor": "José Falero"},
  {"id": "pz229-19", "ed": 229, "tipo": "outro", "chapeu": "quadrinhos", "titulo": "O anjo ri", "linha": "Faremos do vosso cemitério uma praia, e florescer o entulho que vos cobre", "autor": "Joe Sacco"},
  {"id": "pz229-20", "ed": 229, "tipo": "outro", "chapeu": "cartas", "titulo": "Dodecassílabos alexandrinos fajutos"},
  {"id": "pz229-21", "ed": 229, "tipo": "reportagem", "chapeu": "despedida", "titulo": "Vítima do passado", "linha": "A morte de um guarda-freio em Lisboa", "autor": "João Gabriel de Lima"},
  {"id": "pz229-22", "ed": 229, "tipo": "esquina", "chapeu": "esquina", "titulo": "Prolegômenos de golpologia", "linha": "O que alunos de direito aprenderam no julgamento de Bolsonaro", "autor": "Pedro Tavares"},
  {"id": "pz229-23", "ed": 229, "tipo": "esquina", "chapeu": "esquina", "titulo": "Última sessão em Cabul", "linha": "Proprietários de um cinema afegão buscam asilo no Brasil", "autor": "Consuelo Dieguez"},
  {"id": "pz229-24", "ed": 229, "tipo": "esquina", "chapeu": "esquina", "titulo": "Movimentos dissidentes", "linha": "Um festival dedicado à arte de pessoas com deficiência", "autor": "Leandro Aguiar"},
  {"id": "pz229-25", "ed": 229, "tipo": "esquina", "chapeu": "esquina", "titulo": "Divórcio na alta esfera", "linha": "O rompimento de Rubens Menin e João Camargo, que deixou a CNN", "autor": "João Batista Jr."},
  {"id": "pz229-26", "ed": 229, "tipo": "esquina", "chapeu": "esquina", "titulo": "Irmãs de cannabis", "linha": "Uma irmandade na Califórnia que produz derivados de maconha", "autor": "Felippe Aníbal"},
  {"id": "pz229-27", "ed": 229, "tipo": "esquina", "chapeu": "esquina", "titulo": "Joias do desengano", "linha": "O parque fluminense ideal para observar os astros", "autor": "Vivi Fernandes de Lima"},
  {"id": "pz229-28", "ed": 229, "tipo": "esquina", "chapeu": "esquina", "titulo": "A musa do brega", "linha": "Fenômeno nordestino, Priscila Senna agora almeja o Brasil inteiro", "autor": "Felipe Fernandes"},
  {"id": "pz229-29", "ed": 229, "tipo": "outro", "chapeu": "cartuns", "titulo": "19 anos", "autor": "Adão Iturrusgarai, Alberto Benett, Aline Zouvi, Allan Sieber, André Dahmer, Andrício de Souza, Caco Galhardo, Carol Ito, Claudius Ceccon, Cynthia Bonacossa, Daniel Kondo, Fabiane Langona, Gabriel Pardal, Galvão Bertazzi, Laerte Coutinho, Leandro Ilustrado, Paula Villar, Reberson Alexandre e Tracey K. Berglund"},
];
